#!/usr/bin/env bash

function yes_or_no {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0  ;;
            [Nn]*) return 1 ;;
        esac
    done
}

function getfile {

    command -v wget >/dev/null 2>&1
    if [ $? -eq 0 ]
    then
        echo "Downloading $1"
        wget -O $2 $1 -q --show-progress
        return $?
    fi

    command -v curl >/dev/null 2>&1
    if [ $? -eq 0 ]
    then
        echo "Downloading $1"
        curl -o $2 $1 --progress-bar
        return $?
    fi

    echo "Could not find wget nor curl command line tools for downloading file."
    exit 1
}

function check_conda_env
{
    conda info --envs | grep -e "^$1 "
    if [ $? -eq 0 ]
    then
        echo "Conda environment $1 already exists."
        echo "I would like to use it in the installation process."

        msg="Shall I proceeed?"
        yes_or_no $msg && answer="yes" || answer="no"
        if [[ $answer == "no" ]]
        then
            echo "Goodbye!"
            exit 1
        fi
        return 1
    fi
    return 0
}

function anaconda_url
{
    if [ "$(uname)" == "Darwin" ]; then
        url=https://repo.continuum.io/archive/Anaconda2-5.1.0-MacOSX-x86_64.sh
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        url=https://repo.continuum.io/archive/Anaconda2-5.1.0-Linux-x86_64.sh
    else
        echo -n "Unrecognized Operating system. This installer is for"
        echo " Linux and macOS only."
        exit 1
    fi
    echo $url
}

echo "[0/4] Installing StructLMM..."

command -v conda >/dev/null 2>&1
if [ $? -eq 1 ]
then
    echo "I could not find the required conda package manager."
    msg="Shall I install it for you?"
    yes_or_no $msg && answer="yes" || answer="no"

    if [[ $answer == "no" ]]
    then
        echo "Goodbye!"
        exit 0
    else
        getfile $(anaconda_url) Anaconda.sh
        if [ $? -ne 0 ]
        then
            echo "Failed to download the conda package manager."
            exit 1
        fi
        bash Anaconda.sh
        if [ $? -ne 0 ]
        then
            exit 1
        fi

        [ -f ~/.bashrc ] && source ~/.bashrc
        hash -r

        command -v conda >/dev/null 2>&1
        if [ $? -eq 1 ]
        then
            echo "I still cannot find the conda package manager."
            echo -n "Please, make sure it is properly installed so we can "
            echo "proceed."
            exit 1
        fi
    fi
fi

echo "[1/4] Updating the conda package manager..."
conda update -n base conda --yes

source deactivate
check_conda_env struct-lmm

if [ $? -eq 0 ]
then
    echo "[2/4] Creating struct-lmm environment..."
    conda create -n struct-lmm python=2.7 --yes
else
    echo "[2/4] Activating struct-lmm environment..."
fi
source activate struct-lmm

echo "[3/4] Installing dependencies into the struct-lmm environment..."
conda install -c conda-forge limix r r-base r-essentials rpy2 \
                 r-compquadform sphinx sphinx_rtd_theme pip setuptools --yes

echo "[4/4] Installing struct-lmm itself..."
pip install git+https://github.com/limix/struct-lmm.git

echo
echo "Done. To use struct-lmm, please, enter"
echo "  source activate struct-lmm"
echo "Further information can be found at"
echo "  https://struct-lmm.readthedocs.io/"

function cleanup
{
    rm -rf Anaconda.sh >/dev/null 2>&1 || true
}

trap cleanup EXIT
